-- dependent an independent variables for the model to run

SELECT
  patient_id AS patient_id,
  age AS age,
  hospital_outcome AS hospital_outcome,
  CASE WHEN sex = 'MALE' THEN 1 ELSE 0 END AS male,
  vitals_temp_ed_first AS vitals_temp_ed_first,
  vitals_sbp_ed_first AS vitals_sbp_ed_first,
  vitals_dbp_ed_first AS vitals_dbp_ed_first,
  vitals_hr_ed_first AS vitals_hr_ed_first,
  vitals_spo2_ed_first AS vitals_spo2_ed_first,
  pmhx_diabetes AS pmhx_diabetes,
  pmhx_hld AS pmhx_hld,
  pmhx_htn AS pmhx_htn,
  pmhx_ihd AS pmhx_ihd,
  pmhx_ckd AS pmhx_ckd,
  pmhx_copd AS pmhx_copd,
  pmhx_asthma AS pmhx_asthma,
  pmhx_activecancer AS pmhx_activecancer,
  pmhx_chronicliver AS pmhx_chronicliver,
  pmhx_stroke AS pmhx_stroke,
  pmhx_chf AS pmhx_chf,
  pmhx_dementia AS pmhx_dementia,
  lab_rbc AS lab_rbc,
  lab_rdw AS lab_rdw,
  lab_hct AS lab_hct,
  lab_mean_platelet_volume AS lab_mean_platelet_volume,
  lab_neutrophil_percentage AS lab_neutrophil_percentage,
  lab_glucose AS lab_glucose,
  lab_ast AS lab_ast,
  lab_alt AS lab_alt,
  lab_crp AS lab_crp,
  lab_lymphocyte_percentage AS lab_lymphocyte_percentage,
  lab_ddimer AS lab_ddimer,
  lab_leukocyte AS lab_leukocyte,
  lab_ldh AS lab_ldh,
  lab_prothrombin_activity AS lab_prothrombin_activity,
  lab_hemoglobin AS lab_hemoglobin,
  lab_aptt AS lab_aptt,
  lab_lymphocyte AS lab_lymphocyte,
  lab_creatinine AS lab_creatinine,
  lab_inr AS lab_inr,
  lab_neutrophil AS lab_neutrophil,
  lab_sodium AS lab_sodium,
  lab_urea AS lab_urea,
  lab_platelet AS lab_platelet,
  lab_mch AS lab_mch,
  lab_potassium AS lab_potassium,
  lab_mcv AS lab_mcv
FROM
  simul_rep_db.covid_param;
